<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Wed, 10 Aug 2016 08:30:57 +0000
 */
$conf['title'] = '港城百科';
$conf['lang'] = 'zh';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
